### ISSUE TITLE
what's fate-operator built for ?

### ISSUE THREAD

**Issue by SimonCqk** [kubeflow/fate-operator#2]
It seems a totally new project and what is this operator built for ?

**Comment by gaocegege** [comment]
https://github.com/kubeflow/community/pull/335

**Comment by gaocegege** [comment]
It is for Federated ML.

**Comment by SimonCqk** [comment]
Awesome idea! We've considered federated training jobs but the most challenging issues are data accessing across different clusters(sites), I'll keep following this project :)

**Comment by gaocegege** [comment]
We have the proposal for it https://github.com/kubeflow/community/pull/335

Welcome suggestions or contributions.

/cc @LaynePeng
