### ISSUE TITLE
[question] Can we support FATEBoard?

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/fate-operator#6]
I am wondering if we support FATEBoard if we run FateJob on Kubernetes? If we do please add it in the README or other docs.

**Comment by LaynePeng** [comment]
> I am wondering if we support FATEBoard if we run FateJob on Kubernetes? If we do please add it in the README or other docs.

Yes, the FateCluster will install a complete FATE. And FateJob actually submit job to fateflow just like we did in Notebook or command line.
